apiVersion: apps/v1
kind: Deployment
metadata:
  name: mnist-deployment
spec:
  replicas:2
  selector:
    matchLabels:
      app: mnist
  template:
    metadata:
      labels:
        app: mnist
    spec:
      containers:
      - name: mnist
        image: mnist
        ports:
        - containerPort: 8000